*&---------------------------------------------------------------------*
*& Include MV45AFZB - FORM USEREXIT_CHECK_VBAP   (safety net)
*& Implicit enhancement at the start of the FORM.
*&
*& Rejects a NEW item in VA01 for relevant orders. Items copied from the
*& contract carry VBAP-VGBEL; an item entered manually does not.
*& Covers every other way of adding items, e.g. typing into an empty
*& row or another function code than POAN.
*& Sub-items generated by the system (free goods, BOM components:
*& VBAP-UEPOS filled) are allowed.
*&---------------------------------------------------------------------*
ENHANCEMENT 1 zsd_so_con_no_new_item.

  IF t180-trtyp = 'H'                                         " create (VA01)
     AND vbap-vgbel IS INITIAL
     AND vbap-uepos IS INITIAL
     AND vbak-vgbel IS NOT INITIAL
     AND vbak-vgtyp = zcl_sd_so_contract_ctrl=>gc_vgtyp_contract
     AND zcl_sd_so_contract_ctrl=>is_relevant(
           is_vbak    = vbak
           iv_process = zcl_sd_so_contract_ctrl=>gc_process-create ) = abap_true.
    MESSAGE e398(00) WITH 'New items are not allowed for orders'
                          'with reference to contract' vbak-vgbel ''.
  ENDIF.

ENDENHANCEMENT.
