*&---------------------------------------------------------------------*
*& Program        : ZSD_SO_CHG_WF_LOG
*& Transaction    : ZSD_SOCHG_LOG
*& Workflow       : ZSD_SO_CHG_APPR (WS9xxxxxxx)
*& Package        : ZSD
*&---------------------------------------------------------------------*
*& Technical Consultant  : Hassan Diab
*& Functional Consultant : <Functional consultant>
*&---------------------------------------------------------------------*
*& Purpose        : Log monitor of the sales order change approval
*&                  workflow (CH4323).
*&---------------------------------------------------------------------*
*& Created By     : Hassan Diab
*& Created On     : 06.10.2026
*& Request No.    : <Request>
*& Version        : 1.0
*&---------------------------------------------------------------------*
*& Change History
*&---------------------------------------------------------------------*
*& Ver | Date       | Author        | Request No.  | Description
*&-----|------------|---------------|--------------|--------------------
*& 1.0 | 06.10.2026 | Hassan Diab   | <Request>    | Initial Creation
*&---------------------------------------------------------------------*
REPORT ZSD_SO_CHG_WF_LOG.

TABLES ZSD_SO_CHG_LH.

SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME TITLE TEXT-B01.
  PARAMETERS     P_VKORG TYPE VKORG OBLIGATORY.
  SELECT-OPTIONS S_VBELN  FOR ZSD_SO_CHG_LH-VBELN.
  SELECT-OPTIONS S_KUNNR  FOR ZSD_SO_CHG_LH-KUNNR.
  SELECT-OPTIONS S_AUART  FOR ZSD_SO_CHG_LH-AUART.
  SELECT-OPTIONS S_VTWEG  FOR ZSD_SO_CHG_LH-VTWEG.
  SELECT-OPTIONS S_SPART  FOR ZSD_SO_CHG_LH-SPART.
  SELECT-OPTIONS S_CREDAT FOR ZSD_SO_CHG_LH-CREATED_ON.
  SELECT-OPTIONS S_STATUS FOR ZSD_SO_CHG_LH-STATUS.
  SELECT-OPTIONS S_TRGBY  FOR ZSD_SO_CHG_LH-TRIGGER_BY.
SELECTION-SCREEN END OF BLOCK B1.

CLASS LCL_REPORT DEFINITION FINAL.

  PUBLIC SECTION.

    TYPES:
      BEGIN OF TY_OUT,
        STATUS_ICON TYPE ICON_D,
        STATUS_TEXT TYPE CHAR30,
        VBELN       TYPE VBELN_VA,
        CONTRACT    TYPE VBELN_VA,
        KUNNR       TYPE KUNAG,
        CUST_NAME   TYPE NAME1_GP,
        VKORG       TYPE VKORG,
        VTWEG       TYPE VTWEG,
        SPART       TYPE SPART,
        AUART       TYPE AUART,
        CHANGE_TEXT TYPE ZSD_SO_CHG_TEXT,
        L1_ICON     TYPE ICON_D,
        L2_ICON     TYPE ICON_D,
        L3_ICON     TYPE ICON_D,
        L4_ICON     TYPE ICON_D,
        CURR_LEVEL  TYPE ZSD_SO_LEVEL,
        LEVELS      TYPE ZSD_SO_LEVEL,
        CURR_APPR   TYPE AD_NAMTEXT,
        NETWR       TYPE NETWR_AK,
        WAERK       TYPE WAERK,
        CREATED_ON  TYPE DATS,
        CREATED_AT  TYPE TIMS,
        FINISHED_ON TYPE DATS,
        FINISHED_AT TYPE TIMS,
        TRIGGER_EVT TYPE SIBFEVENT,
        TRIGGER_BY  TYPE XUBNAME,
        TRIGGER_ON  TYPE DATS,
        TRIGGER_AT  TYPE TIMS,
        REPLACED_BY TYPE SYSUUID_C32,
        WF_ID       TYPE SWW_WIID,
        LOG_ID      TYPE SYSUUID_C32,
      END OF TY_OUT .
    TYPES TT_OUT TYPE STANDARD TABLE OF TY_OUT WITH DEFAULT KEY .

    TYPES:
      BEGIN OF TY_EVT,
        ICON       TYPE ICON_D,
        EVENT_TEXT TYPE CHAR30,
        SEQNR      TYPE ZSD_SO_CHG_LE-SEQNR,
        APPR_LEVEL TYPE ZSD_SO_LEVEL,
        UNAME      TYPE XUBNAME,
        TEXT       TYPE ZSD_SO_CHG_LE-TEXT,
        CREATED_ON TYPE DATS,
        CREATED_AT TYPE TIMS,
        CREATED_BY TYPE SYUNAME,
      END OF TY_EVT .
    TYPES TT_EVT TYPE STANDARD TABLE OF TY_EVT WITH DEFAULT KEY .

    METHODS RUN .

  PRIVATE SECTION.

    DATA MT_OUT TYPE TT_OUT .
    DATA MO_ALV TYPE REF TO CL_SALV_TABLE .

    METHODS SELECT_DATA .
    METHODS DISPLAY .
    METHODS SHOW_EVENTS
      IMPORTING
        !IV_LOG_ID TYPE SYSUUID_C32 .
    METHODS SET_COLUMN
      IMPORTING
        !IO_COLUMNS TYPE REF TO CL_SALV_COLUMNS_TABLE
        !IV_NAME    TYPE LVC_FNAME
        !IV_TEXT    TYPE CSEQUENCE OPTIONAL
        !IV_ICON    TYPE ABAP_BOOL OPTIONAL
        !IV_HOTSPOT TYPE ABAP_BOOL OPTIONAL
        !IV_HIDE    TYPE ABAP_BOOL OPTIONAL
        !IV_CURR    TYPE LVC_FNAME OPTIONAL .

    METHODS ON_DOUBLE_CLICK
      FOR EVENT DOUBLE_CLICK OF CL_SALV_EVENTS_TABLE
      IMPORTING ROW COLUMN .
    METHODS ON_LINK_CLICK
      FOR EVENT LINK_CLICK OF CL_SALV_EVENTS_TABLE
      IMPORTING ROW COLUMN .

ENDCLASS.


CLASS LCL_REPORT IMPLEMENTATION.

  METHOD RUN.

    SELECT_DATA( ).

    IF MT_OUT IS INITIAL.
      MESSAGE 'No workflow log found for the selection'(M01) TYPE 'S' DISPLAY LIKE 'W'.
      RETURN.
    ENDIF.

    DISPLAY( ).

  ENDMETHOD.


  METHOD SELECT_DATA.

    DATA: LT_HEAD   TYPE STANDARD TABLE OF ZSD_SO_CHG_LH,
          LS_HEAD   TYPE ZSD_SO_CHG_LH,
          LT_LEVELS TYPE STANDARD TABLE OF ZSD_SO_CHG_LL,
          LS_LEVEL  TYPE ZSD_SO_CHG_LL,
          LS_OUT    TYPE TY_OUT,
          LV_POS    TYPE I.

    CLEAR MT_OUT.

    SELECT * FROM ZSD_SO_CHG_LH INTO TABLE LT_HEAD
      WHERE VKORG      = P_VKORG
        AND VBELN      IN S_VBELN
        AND KUNNR      IN S_KUNNR
        AND AUART      IN S_AUART
        AND VTWEG      IN S_VTWEG
        AND SPART      IN S_SPART
        AND CREATED_ON IN S_CREDAT
        AND STATUS     IN S_STATUS
        AND TRIGGER_BY IN S_TRGBY.

    IF LT_HEAD IS INITIAL.
      RETURN.
    ENDIF.

    SELECT * FROM ZSD_SO_CHG_LL INTO TABLE LT_LEVELS
      FOR ALL ENTRIES IN LT_HEAD
      WHERE LOG_ID = LT_HEAD-LOG_ID.

    SORT LT_LEVELS BY LOG_ID APPR_LEVEL.
    SORT LT_HEAD BY CREATED_ON DESCENDING CREATED_AT DESCENDING.

    LOOP AT LT_HEAD INTO LS_HEAD.

      CLEAR LS_OUT.
      MOVE-CORRESPONDING LS_HEAD TO LS_OUT.

      LS_OUT-STATUS_ICON = ZCL_SD_SO_CHG_LOG=>GET_STATUS_ICON( LS_HEAD-STATUS ).
      LS_OUT-STATUS_TEXT = ZCL_SD_SO_CHG_LOG=>GET_STATUS_TEXT( LS_HEAD-STATUS ).

      " level columns by position (levels may be numbered 01/02/.. or 10/20/..)
      CLEAR LV_POS.
      LOOP AT LT_LEVELS INTO LS_LEVEL WHERE LOG_ID = LS_HEAD-LOG_ID.
        LV_POS = LV_POS + 1.
        CASE LV_POS.
          WHEN 1. LS_OUT-L1_ICON = ZCL_SD_SO_CHG_LOG=>GET_LEVEL_ICON( LS_LEVEL-STATUS ).
          WHEN 2. LS_OUT-L2_ICON = ZCL_SD_SO_CHG_LOG=>GET_LEVEL_ICON( LS_LEVEL-STATUS ).
          WHEN 3. LS_OUT-L3_ICON = ZCL_SD_SO_CHG_LOG=>GET_LEVEL_ICON( LS_LEVEL-STATUS ).
          WHEN 4. LS_OUT-L4_ICON = ZCL_SD_SO_CHG_LOG=>GET_LEVEL_ICON( LS_LEVEL-STATUS ).
        ENDCASE.
        IF LS_LEVEL-APPR_LEVEL = LS_HEAD-CURR_LEVEL
           AND LS_HEAD-STATUS = ZCL_SD_SO_CHG_LOG=>GC_STATUS-IN_PROCESS.
          LS_OUT-CURR_APPR = LS_LEVEL-FULL_NAME.
        ENDIF.
      ENDLOOP.

      APPEND LS_OUT TO MT_OUT.

    ENDLOOP.

  ENDMETHOD.


  METHOD DISPLAY.

    DATA: LO_COLUMNS   TYPE REF TO CL_SALV_COLUMNS_TABLE,
          LO_EVENTS    TYPE REF TO CL_SALV_EVENTS_TABLE,
          LO_FUNCTIONS TYPE REF TO CL_SALV_FUNCTIONS_LIST,
          LO_DISPLAY   TYPE REF TO CL_SALV_DISPLAY_SETTINGS,
          LX_SALV      TYPE REF TO CX_SALV_MSG,
          LV_TITLE     TYPE LVC_TITLE.

    TRY.
        CL_SALV_TABLE=>FACTORY( IMPORTING R_SALV_TABLE = MO_ALV
                                CHANGING  T_TABLE      = MT_OUT ).
      CATCH CX_SALV_MSG INTO LX_SALV.
        MESSAGE LX_SALV TYPE 'E'.
        RETURN.
    ENDTRY.

    LO_FUNCTIONS = MO_ALV->GET_FUNCTIONS( ).
    LO_FUNCTIONS->SET_ALL( ABAP_TRUE ).

    LO_DISPLAY = MO_ALV->GET_DISPLAY_SETTINGS( ).
    LO_DISPLAY->SET_STRIPED_PATTERN( ABAP_TRUE ).
    LV_TITLE = 'Sales order change approval - workflow log'(T01).
    LO_DISPLAY->SET_LIST_HEADER( LV_TITLE ).

    LO_COLUMNS = MO_ALV->GET_COLUMNS( ).
    LO_COLUMNS->SET_OPTIMIZE( ABAP_TRUE ).

    SET_COLUMN( IO_COLUMNS = LO_COLUMNS IV_NAME = 'STATUS_ICON' IV_TEXT = 'Status'(H01)   IV_ICON = ABAP_TRUE ).
    SET_COLUMN( IO_COLUMNS = LO_COLUMNS IV_NAME = 'STATUS_TEXT' IV_TEXT = 'Status text'(H02) ).
    SET_COLUMN( IO_COLUMNS = LO_COLUMNS IV_NAME = 'VBELN'       IV_HOTSPOT = ABAP_TRUE ).
    SET_COLUMN( IO_COLUMNS = LO_COLUMNS IV_NAME = 'CONTRACT'    IV_TEXT = 'Contract'(H03) IV_HOTSPOT = ABAP_TRUE ).
    SET_COLUMN( IO_COLUMNS = LO_COLUMNS IV_NAME = 'CHANGE_TEXT' IV_TEXT = 'Changes'(H26) ).
    SET_COLUMN( IO_COLUMNS = LO_COLUMNS IV_NAME = 'L1_ICON'     IV_TEXT = 'Level 1'(H04)  IV_ICON = ABAP_TRUE ).
    SET_COLUMN( IO_COLUMNS = LO_COLUMNS IV_NAME = 'L2_ICON'     IV_TEXT = 'Level 2'(H05)  IV_ICON = ABAP_TRUE ).
    SET_COLUMN( IO_COLUMNS = LO_COLUMNS IV_NAME = 'L3_ICON'     IV_TEXT = 'Level 3'(H06)  IV_ICON = ABAP_TRUE ).
    SET_COLUMN( IO_COLUMNS = LO_COLUMNS IV_NAME = 'L4_ICON'     IV_TEXT = 'Level 4'(H07)  IV_ICON = ABAP_TRUE ).
    SET_COLUMN( IO_COLUMNS = LO_COLUMNS IV_NAME = 'CURR_LEVEL'  IV_TEXT = 'Current level'(H08) ).
    SET_COLUMN( IO_COLUMNS = LO_COLUMNS IV_NAME = 'LEVELS'      IV_TEXT = 'Levels'(H09) ).
    SET_COLUMN( IO_COLUMNS = LO_COLUMNS IV_NAME = 'CURR_APPR'   IV_TEXT = 'Waiting for'(H10) ).
    SET_COLUMN( IO_COLUMNS = LO_COLUMNS IV_NAME = 'NETWR'       IV_TEXT = 'Net value'(H11) IV_CURR = 'WAERK' ).
    SET_COLUMN( IO_COLUMNS = LO_COLUMNS IV_NAME = 'CREATED_ON'  IV_TEXT = 'Started on'(H16) ).
    SET_COLUMN( IO_COLUMNS = LO_COLUMNS IV_NAME = 'CREATED_AT'  IV_TEXT = 'Started at'(H17) ).
    SET_COLUMN( IO_COLUMNS = LO_COLUMNS IV_NAME = 'FINISHED_ON' IV_TEXT = 'Finished on'(H18) ).
    SET_COLUMN( IO_COLUMNS = LO_COLUMNS IV_NAME = 'FINISHED_AT' IV_TEXT = 'Finished at'(H19) ).
    SET_COLUMN( IO_COLUMNS = LO_COLUMNS IV_NAME = 'TRIGGER_EVT' IV_TEXT = 'Trigger event'(H22) ).
    SET_COLUMN( IO_COLUMNS = LO_COLUMNS IV_NAME = 'TRIGGER_BY'  IV_TEXT = 'Changed by'(H23) ).
    SET_COLUMN( IO_COLUMNS = LO_COLUMNS IV_NAME = 'TRIGGER_ON'  IV_TEXT = 'Changed on'(H24) ).
    SET_COLUMN( IO_COLUMNS = LO_COLUMNS IV_NAME = 'TRIGGER_AT'  IV_TEXT = 'Changed at'(H25) ).
    SET_COLUMN( IO_COLUMNS = LO_COLUMNS IV_NAME = 'REPLACED_BY' IV_HIDE = ABAP_TRUE ).
    SET_COLUMN( IO_COLUMNS = LO_COLUMNS IV_NAME = 'WF_ID'       IV_TEXT = 'Workflow'(H21) IV_HOTSPOT = ABAP_TRUE ).
    SET_COLUMN( IO_COLUMNS = LO_COLUMNS IV_NAME = 'LOG_ID'      IV_HIDE = ABAP_TRUE ).

    LO_EVENTS = MO_ALV->GET_EVENT( ).
    SET HANDLER ON_DOUBLE_CLICK FOR LO_EVENTS.
    SET HANDLER ON_LINK_CLICK   FOR LO_EVENTS.

    MO_ALV->DISPLAY( ).

  ENDMETHOD.


  METHOD SET_COLUMN.

    DATA: LO_COLUMN TYPE REF TO CL_SALV_COLUMN_TABLE,
          LV_SHORT  TYPE SCRTEXT_S,
          LV_MEDIUM TYPE SCRTEXT_M,
          LV_LONG   TYPE SCRTEXT_L.

    TRY.
        LO_COLUMN ?= IO_COLUMNS->GET_COLUMN( IV_NAME ).
      CATCH CX_SALV_NOT_FOUND.
        RETURN.
    ENDTRY.

    IF IV_TEXT IS NOT INITIAL.
      LV_SHORT  = IV_TEXT.
      LV_MEDIUM = IV_TEXT.
      LV_LONG   = IV_TEXT.
      LO_COLUMN->SET_SHORT_TEXT( LV_SHORT ).
      LO_COLUMN->SET_MEDIUM_TEXT( LV_MEDIUM ).
      LO_COLUMN->SET_LONG_TEXT( LV_LONG ).
    ENDIF.

    IF IV_ICON = ABAP_TRUE.
      LO_COLUMN->SET_ICON( IF_SALV_C_BOOL_SAP=>TRUE ).
      LO_COLUMN->SET_ALIGNMENT( IF_SALV_C_ALIGNMENT=>CENTERED ).
    ENDIF.

    IF IV_HOTSPOT = ABAP_TRUE.
      LO_COLUMN->SET_CELL_TYPE( IF_SALV_C_CELL_TYPE=>HOTSPOT ).
    ENDIF.

    IF IV_HIDE = ABAP_TRUE.
      LO_COLUMN->SET_VISIBLE( ABAP_FALSE ).
    ENDIF.

    IF IV_CURR IS NOT INITIAL.
      TRY.
          LO_COLUMN->SET_CURRENCY_COLUMN( IV_CURR ).
        CATCH CX_SALV_NOT_FOUND CX_SALV_DATA_ERROR.
      ENDTRY.
    ENDIF.

  ENDMETHOD.


  METHOD ON_DOUBLE_CLICK.

    DATA LS_OUT TYPE TY_OUT.

    READ TABLE MT_OUT INTO LS_OUT INDEX ROW.
    IF SY-SUBRC = 0.
      SHOW_EVENTS( LS_OUT-LOG_ID ).
    ENDIF.

  ENDMETHOD.


  METHOD ON_LINK_CLICK.

    DATA LS_OUT TYPE TY_OUT.

    READ TABLE MT_OUT INTO LS_OUT INDEX ROW.
    IF SY-SUBRC <> 0.
      RETURN.
    ENDIF.

    CASE COLUMN.
      WHEN 'VBELN'.
        SET PARAMETER ID 'AUN' FIELD LS_OUT-VBELN.
        CALL TRANSACTION 'VA03' AND SKIP FIRST SCREEN.      "#EC CI_CALLTA
      WHEN 'CONTRACT'.
        IF LS_OUT-CONTRACT IS NOT INITIAL.
          SET PARAMETER ID 'KTN' FIELD LS_OUT-CONTRACT.
          CALL TRANSACTION 'VA43' AND SKIP FIRST SCREEN.    "#EC CI_CALLTA
        ENDIF.
      WHEN 'WF_ID'.
        IF LS_OUT-WF_ID IS NOT INITIAL.
          CALL FUNCTION 'SWL_WI_DISPLAY'
            EXPORTING
              WI_ID  = LS_OUT-WF_ID
            EXCEPTIONS
              OTHERS = 1.
          IF SY-SUBRC <> 0.
            MESSAGE 'Workflow log cannot be displayed'(M02) TYPE 'S' DISPLAY LIKE 'E'.
          ENDIF.
        ENDIF.
    ENDCASE.

  ENDMETHOD.


  METHOD SHOW_EVENTS.

    DATA: LT_EVENTS  TYPE ZCL_SD_SO_CHG_LOG=>TT_EVENTS,
          LS_EVENT   TYPE ZSD_SO_CHG_LE,
          LT_EVT     TYPE TT_EVT,
          LS_EVT     TYPE TY_EVT,
          LO_POPUP   TYPE REF TO CL_SALV_TABLE,
          LO_COLUMNS TYPE REF TO CL_SALV_COLUMNS_TABLE,
          LO_DISPLAY TYPE REF TO CL_SALV_DISPLAY_SETTINGS,
          LX_SALV    TYPE REF TO CX_SALV_MSG,
          LV_TITLE   TYPE LVC_TITLE.

    LT_EVENTS = ZCL_SD_SO_CHG_LOG=>GET_EVENTS( IV_LOG_ID ).

    LOOP AT LT_EVENTS INTO LS_EVENT.
      CLEAR LS_EVT.
      MOVE-CORRESPONDING LS_EVENT TO LS_EVT.
      LS_EVT-ICON       = ZCL_SD_SO_CHG_LOG=>GET_EVENT_ICON( LS_EVENT-EVENT ).
      LS_EVT-EVENT_TEXT = ZCL_SD_SO_CHG_LOG=>GET_EVENT_TEXT( LS_EVENT-EVENT ).
      APPEND LS_EVT TO LT_EVT.
    ENDLOOP.

    TRY.
        CL_SALV_TABLE=>FACTORY( IMPORTING R_SALV_TABLE = LO_POPUP
                                CHANGING  T_TABLE      = LT_EVT ).
      CATCH CX_SALV_MSG INTO LX_SALV.
        MESSAGE LX_SALV TYPE 'S' DISPLAY LIKE 'E'.
        RETURN.
    ENDTRY.

    LO_COLUMNS = LO_POPUP->GET_COLUMNS( ).
    LO_COLUMNS->SET_OPTIMIZE( ABAP_TRUE ).
    SET_COLUMN( IO_COLUMNS = LO_COLUMNS IV_NAME = 'ICON'       IV_TEXT = 'Step'(E01) IV_ICON = ABAP_TRUE ).
    SET_COLUMN( IO_COLUMNS = LO_COLUMNS IV_NAME = 'EVENT_TEXT' IV_TEXT = 'Event'(E02) ).
    SET_COLUMN( IO_COLUMNS = LO_COLUMNS IV_NAME = 'SEQNR'      IV_TEXT = 'No.'(E03) ).
    SET_COLUMN( IO_COLUMNS = LO_COLUMNS IV_NAME = 'APPR_LEVEL' IV_TEXT = 'Level'(E04) ).
    SET_COLUMN( IO_COLUMNS = LO_COLUMNS IV_NAME = 'UNAME'      IV_TEXT = 'User'(E05) ).
    SET_COLUMN( IO_COLUMNS = LO_COLUMNS IV_NAME = 'TEXT'       IV_TEXT = 'Details'(E06) ).
    SET_COLUMN( IO_COLUMNS = LO_COLUMNS IV_NAME = 'CREATED_ON' IV_TEXT = 'Date'(E07) ).
    SET_COLUMN( IO_COLUMNS = LO_COLUMNS IV_NAME = 'CREATED_AT' IV_TEXT = 'Time'(E08) ).
    SET_COLUMN( IO_COLUMNS = LO_COLUMNS IV_NAME = 'CREATED_BY' IV_TEXT = 'Logged by'(E09) ).

    LO_DISPLAY = LO_POPUP->GET_DISPLAY_SETTINGS( ).
    LV_TITLE = 'Workflow timeline'(T02).
    LO_DISPLAY->SET_LIST_HEADER( LV_TITLE ).

    LO_POPUP->SET_SCREEN_POPUP( START_COLUMN = 5
                                END_COLUMN   = 170
                                START_LINE   = 3
                                END_LINE     = 25 ).
    LO_POPUP->DISPLAY( ).

  ENDMETHOD.

ENDCLASS.

START-OF-SELECTION.
  DATA GO_REPORT TYPE REF TO LCL_REPORT.
  CREATE OBJECT GO_REPORT.
  GO_REPORT->RUN( ).
